# name: NanoPI R3S (Keep)

# on:
#   workflow_dispatch:  # Can run manually
#   schedule:
#     - cron:  '01 15 */20 * *'

# jobs:
#     build:
#         name: Build
#         runs-on: ubuntu-latest

#         steps:
#             - name: Checkout
#               uses: actions/checkout@main
#               with:
#                 repository: 'immortalwrt/immortalwrt'
#                 ref: 'openwrt-24.10'
                
#             - name: Free Disk Space
#               uses: jlumbroso/free-disk-space@main
#               with:
#                 tool-cache: true
#                 android: true
#                 dotnet: true
#                 haskell: true
#                 large-packages: true
#                 docker-images: true
#                 swap-storage: true
                
#             - name: Install Packages
#               run: |
#                 sudo apt update -y && \
#                 sudo apt install -y \
#                 make git gcc g++ ack autoconf automake autopoint binutils bison \
#                 libncurses5-dev libncursesw5-dev build-essential bzip2 ccache cmake cpio \
#                 unzip bzip2 wget python3 file rsync gawk xz-utils curl device-tree-compiler \
#                 fastjar flex gettext gperf haveged help2man intltool libelf-dev libssl-dev \
#                 libtool lrzsz mkisofs nano ninja-build p7zip patch pkgconf wget vim xxd \
#                 software-properties-common python3-pyelftools python3-setuptools swig \
#                 python3-dev
            
#             - name: Install Go
#               run: |
#                 sudo add-apt-repository ppa:longsleep/golang-backports && \
#                 sudo apt update && \
#                 sudo apt install -y golang-go 
            
#             - name: Configure Feeds
#               run: |
#                 echo "src-git pw2 https://github.com/xiaorouji/openwrt-passwall2" >> feeds.conf.default
#                 ./scripts/feeds update -a
#                 ./scripts/feeds install -a
              
#             - name: Generate Config
#               run: |
#                 echo "CONFIG_TARGET_rockchip=y\n" > .config
#                 echo "CONFIG_TARGET_rockchip_armv8=y\n" >> .config
#                 echo "CONFIG_TARGET_rockchip_armv8_DEVICE_friendlyarm_nanopi-r3s=y\n" >> .config

#                 echo "CONFIG_PACKAGE_dnsmasq=m\n" >> .config
#                 echo "CONFIG_PACKAGE_dnsmasq-full=y\n" >> .config
#                 echo "CONFIG_PACKAGE_luci=y\n" >> .config

#                 echo "CONFIG_PACKAGE_luci-app-passwall2=y\n" >> .config
#                 echo "CONFIG_PACKAGE_luci-app-passwall2_Iptables_Transparent_Proxy=n\n" >> .config
#                 echo "CONFIG_PACKAGE_luci-app-passwall2_Nftables_Transparent_Proxy=y\n" >> .config
#                 echo "CONFIG_PACKAGE_luci-app-passwall2_INCLUDE_Haproxy=n\n" >> .config
#                 echo "CONFIG_PACKAGE_luci-app-passwall2_INCLUDE_Hysteria=n\n" >> .config
#                 echo "CONFIG_PACKAGE_luci-app-passwall2_INCLUDE_NaiveProxy=n\n" >> .config
#                 echo "CONFIG_PACKAGE_luci-app-passwall2_INCLUDE_Shadowsocks_Libev_Client=n\n" >> .config
#                 echo "CONFIG_PACKAGE_luci-app-passwall2_INCLUDE_Shadowsocks_Libev_Server=n\n" >> .config
#                 echo "CONFIG_PACKAGE_luci-app-passwall2_INCLUDE_Shadowsocks_Rust_Client=n\n" >> .config
#                 echo "CONFIG_PACKAGE_luci-app-passwall2_INCLUDE_Shadowsocks_Rust_Server=n\n" >> .config
#                 echo "CONFIG_PACKAGE_luci-app-passwall2_INCLUDE_ShadowsocksR_Libev_Client=n\n" >> .config
#                 echo "CONFIG_PACKAGE_luci-app-passwall2_INCLUDE_ShadowsocksR_Libev_Server=n\n" >> .config
#                 echo "CONFIG_PACKAGE_luci-app-passwall2_INCLUDE_Simple_Obfs=n\n" >> .config
#                 echo "CONFIG_PACKAGE_luci-app-passwall2_INCLUDE_SingBox=n\n" >> .config
#                 echo "CONFIG_PACKAGE_luci-app-passwall2_INCLUDE_tuic_client=n\n" >> .config
#                 echo "CONFIG_PACKAGE_luci-app-passwall2_INCLUDE_V2ray_Plugin=n\n" >> .config

#                 echo "CONFIG_PACKAGE_adguardhome=y\n" >> .config
#                 echo "CONFIG_PACKAGE_parted=y\n" >> .config
#                 echo "CONFIG_PACKAGE_losetup=y\n" >> .config
#                 echo "CONFIG_PACKAGE_resize2fs=y\n" >> .config

#                 make defconfig

#                 sed -i 's/CONFIG_TARGET_KERNEL_PARTSIZE=16/CONFIG_TARGET_KERNEL_PARTSIZE=32/g' .config
#                 sed -i 's/CONFIG_TARGET_ROOTFS_PARTSIZE=104/CONFIG_TARGET_ROOTFS_PARTSIZE=512/g' .config

#             - name: Download Sources
#               run: make download -j$(nproc)

#             - name: Build Tools
#               run: make tools/install -j$(nproc)

#             - name: Build Toolchain
#               run: make toolchain/install -j$(nproc)

#             - name: Build Images
#               run: make -j$(nproc)

#             - name: TAR Output
#               run: tar -cvf nanopi-r3s-images.tar bin/targets/rockchip/armv8

#             - name: Upload Artifacts
#               uses: actions/upload-artifact@main
#               with:
#                 name: nanopi-r3s-images
#                 path: nanopi-r3s-images.tar

#     release:
#           name: Make Release
#           runs-on: ubuntu-latest
#           needs: build

#           steps:
#             - name: Download Artifacts
#               uses: actions/download-artifact@main
#               with:
#                 name: nanopi-r3s-images

#             - name: Extract Artifacts
#               run: tar xf nanopi-r3s-images.tar

#             - name: Get The Current Date
#               run: echo "NOW=$(date +%F)" >> $GITHUB_ENV

#             - name: Create Release
#               uses: "marvinpinto/action-automatic-releases@latest"
#               with:
#                 repo_token: "${{ github.token }}"
#                 prerelease: false
#                 title: "NanoPI R3S v24.10"
#                 automatic_release_tag: "r3s-${{ env.NOW }}"
#                 files: bin/targets/rockchip/armv8/*
